apiVersion: v1
kind: Service
metadata:
    name: maslocompanionserver
spec:
    type: NodePort
    selector:
        app: maslocompanionserver
    ports:
    -   protocol: TCP
        port: 3000
        targetPort: 8080